version: 2

models:
    - name: rentaldata
      description: "rental details , customer, inventory, film"
      columns:
          - name: title
            description: "film title name "
            tests:
                - unique
                - not_null